blank_issues_enabled: true
contact_links:
  - name: Como adicionar conteúdo
    url: https://neteinstein.github.io/Campinacios/Wikin%C3%A1cios/Conte%C3%BAdos.html
    about: Para quem prefere editar as páginas directamente no GitHub.
